[package]
name = "e05-params_and_return"
version = "0.1.0"
edition = "2024"

[lib]
name = "e05_params_and_return_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }