[package]
name = "p18-clipboard_notify"
version = "0.1.0"
edition = "2024"

[lib]
name = "p18_clipboard_notify_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }