[package]
name = "a06-exchange_rate"
version = "0.1.0"
edition = "2024"

[lib]
name = "a06_exchange_rate_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tauri-plugin-http = { workspace = true }
tauri-plugin-store = { workspace = true }