[package]
name = "e38-os_opener-answer"
version = "0.1.0"
edition = "2024"

[lib]
name = "e38_os_opener_answer_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tauri-plugin-os = { workspace = true }
tauri-plugin-opener = { workspace = true }