[package]
name = "e03-run_and_build"
version = "0.1.0"
edition = "2024"

[lib]
name = "e03_run_and_build_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }