[package]
name = "a01-todo-answer"
version = "0.1.0"
edition = "2024"

[lib]
name = "a01_todo_answer_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }