[package]
name = "leptos-sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.20", features = ["csr", "nightly"]}
web-sys = { version = "0.3", features = ["Window", "Location"]}
console_error_panic_hook = "0.1.7"

[workspace]
members = ["."]
resolver = "2"
