 [package]
 name = "e229_shell_nodejs"
 version = "0.1.0"
 edition = "2021"
 
 [lib]
 name = "e229_shell_nodejs_lib"
 crate-type = ["staticlib", "cdylib", "rlib"]
 
 [build-dependencies]
 tauri-build.workspace = true
 
 [dependencies]
 tauri.workspace = true
 serde.workspace = true
 serde_json.workspace = true
 thiserror.workspace = true
