[package]
name = "a04-image_viewer"
version = "0.1.0"
edition = "2024"

[lib]
name = "a04_image_viewer_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
tauri = { workspace = true, features = ["protocol-asset"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }